# whole_bam : "/home/shuaiw/borg/all_borg/XRSBK_20221007_S64018_PL100268287-1_C01.align.bam"
# whole_ref : "/home/shuaiw/borg/all_borg/all_borg.fasta"
# work_dir : "/home/shuaiw/methylation/data/borg/new_test4"


# whole_bam : "/home/shuaiw/methylation/data/borg/b_contigs/10.align.bam"
# whole_ref : "/home/shuaiw/methylation/data/borg/b_contigs/contigs/10.fa"
# work_dir : "/home/shuaiw/methylation/data/borg/new_test4"


whole_bam : "/home/shuaiw/methylation/data/borg/large_contigs/XRSBK_20221007_S64018_PL100268287-1_C01.align.bam"
whole_ref : "/home/shuaiw/methylation/data/borg/contigs/large.contigs.fa"
work_dir : "/home/shuaiw/methylation/data/borg/new_test5"
maxAlignments : 100000 
read_type: "subreads"
