whole_bam : "/home/shuaiw/methylation/data/borg/large_contigs/XRSBK_20221007_S64018_PL100268287-1_C01.align.bam"
whole_ref : "/home/shuaiw/methylation/data/borg/contigs/large.contigs.fa"
work_dir : "/home/shuaiw/methylation/data/borg/new_test5"
maxAlignments : 100000 
read_type: "subreads"
max_NM: 
min_len: 50000
