whole_bam : "/home/shuaiw/methylation/data/borg/large_contigs/XRSBK_20221007_S64018_PL100268287-1_C01.align.bam"
whole_ref : "/home/shuaiw/methylation/data/borg/contigs/large.contigs.fa"
work_dir : "/home/shuaiw/methylation/data/borg/new_test5"
maxAlignments : 100000 
read_type: "subreads"
max_NM: 
min_len: 50000
min_cov: 3
kmer_mean_db: 
kmer_num_db:
clean: True
min_frac: 0.5     ## min methylation fraction to keep a motif
min_sites: 100        ## min number of methylation sites to keep a motif
min_score: 30         ## min score for modification determination
plasmid_file: NA
