nohup bash batch/methy_isolation_part_0.sh &
nohup bash batch/methy_isolation_part_1.sh &
nohup bash batch/methy_isolation_part_2.sh &
nohup bash batch/methy_isolation_part_3.sh &
nohup bash batch/methy_isolation_part_4.sh &
nohup bash batch/methy_isolation_part_5.sh &
nohup bash batch/methy_isolation_part_6.sh &
nohup bash batch/methy_isolation_part_7.sh &
nohup bash batch/methy_isolation_part_8.sh &
nohup bash batch/methy_isolation_part_9.sh &
