sbatch  --partition standard --wrap "python /home/shuaiw/Methy/main.py \
                --work_dir /home/shuaiw/borg/paper/run2/infant_28/infant_28_methylation2 \
                --whole_bam /home/shuaiw/borg/paper/run2/infant_28/infant_28.align.bam \
                --whole_ref /home/shuaiw/borg/paper/run2/infant_28/infant_28.hifiasm.p_ctg.rename.fa \
                --read_type hifi \
                --min_len 1000 \
                --max_NM 30000000 \
                --min_cov 1 \
                --min_frac 0.4 \
                --min_score 30 \
                --min_sites 30 \
                --mge_file /home/shuaiw/borg/paper/run2/infant_28/all_mge.tsv \
                --threads 64" \
                --job-name=infant_28_test
sbatch  --partition standard --wrap "python /home/shuaiw/Methy/main.py \
                --work_dir /home/shuaiw/borg/paper/run2/soil_s3_2/soil_s3_2_methylation2 \
                --whole_bam /home/shuaiw/borg/paper/run2/soil_s3_2/soil_s3_2.align.bam \
                --whole_ref /home/shuaiw/borg/paper/run2/soil_s3_2/soil_s3_2.hifiasm.p_ctg.rename.fa \
                --read_type hifi \
                --min_len 1000 \
                --max_NM 30000000 \
                --min_cov 1 \
                --min_frac 0.4 \
                --min_score 30 \
                --min_sites 30 \
                --mge_file /home/shuaiw/borg/paper/run2/soil_s3_2/all_mge.tsv \
                --threads 64" \
                --job-name=soil_s3_2_test
sbatch  --partition standard --wrap "python /home/shuaiw/Methy/main.py \
                --work_dir /home/shuaiw/borg/paper/run2/soil_s4_2/soil_s4_2_methylation2 \
                --whole_bam /home/shuaiw/borg/paper/run2/soil_s4_2/soil_s4_2.align.bam \
                --whole_ref /home/shuaiw/borg/paper/run2/soil_s4_2/soil_s4_2.hifiasm.p_ctg.rename.fa \
                --read_type hifi \
                --min_len 1000 \
                --max_NM 30000000 \
                --min_cov 1 \
                --min_frac 0.4 \
                --min_score 30 \
                --min_sites 30 \
                --mge_file /home/shuaiw/borg/paper/run2/soil_s4_2/all_mge.tsv \
                --threads 64" \
                --job-name=soil_s4_2_test
sbatch  --partition standard --wrap "python /home/shuaiw/Methy/main.py \
                --work_dir /home/shuaiw/borg/paper/run2/soil_s1_2/soil_s1_2_methylation2 \
                --whole_bam /home/shuaiw/borg/paper/run2/soil_s1_2/soil_s1_2.align.bam \
                --whole_ref /home/shuaiw/borg/paper/run2/soil_s1_2/soil_s1_2.hifiasm.p_ctg.rename.fa \
                --read_type hifi \
                --min_len 1000 \
                --max_NM 30000000 \
                --min_cov 1 \
                --min_frac 0.4 \
                --min_score 30 \
                --min_sites 30 \
                --mge_file /home/shuaiw/borg/paper/run2/soil_s1_2/all_mge.tsv \
                --threads 64" \
                --job-name=soil_s1_2_test
sbatch  --partition standard --wrap "python /home/shuaiw/Methy/main.py \
                --work_dir /home/shuaiw/borg/paper/run2/SRR14074352_human/SRR14074352_human_methylation2 \
                --whole_bam /home/shuaiw/borg/paper/run2/SRR14074352_human/SRR14074352_human.align.bam \
                --whole_ref /home/shuaiw/borg/paper/run2/SRR14074352_human/SRR14074352_human.hifiasm.p_ctg.rename.fa \
                --read_type hifi \
                --min_len 1000 \
                --max_NM 30000000 \
                --min_cov 1 \
                --min_frac 0.4 \
                --min_score 30 \
                --min_sites 30 \
                --mge_file /home/shuaiw/borg/paper/run2/SRR14074352_human/all_mge.tsv \
                --threads 64" \
                --job-name=SRR14074352_human_test
sbatch  --partition standard --wrap "python /home/shuaiw/Methy/main.py \
                --work_dir /home/shuaiw/borg/paper/run2/SRR23446539_sugarcane/SRR23446539_sugarcane_methylation2 \
                --whole_bam /home/shuaiw/borg/paper/run2/SRR23446539_sugarcane/SRR23446539_sugarcane.align.bam \
                --whole_ref /home/shuaiw/borg/paper/run2/SRR23446539_sugarcane/SRR23446539_sugarcane.hifiasm.p_ctg.rename.fa \
                --read_type hifi \
                --min_len 1000 \
                --max_NM 30000000 \
                --min_cov 1 \
                --min_frac 0.4 \
                --min_score 30 \
                --min_sites 30 \
                --mge_file /home/shuaiw/borg/paper/run2/SRR23446539_sugarcane/all_mge.tsv \
                --threads 64" \
                --job-name=SRR23446539_sugarcane_test
sbatch  --partition standard --wrap "python /home/shuaiw/Methy/main.py \
                --work_dir /home/shuaiw/borg/paper/run2/SRR23446540_sugarcane/SRR23446540_sugarcane_methylation2 \
                --whole_bam /home/shuaiw/borg/paper/run2/SRR23446540_sugarcane/SRR23446540_sugarcane.align.bam \
                --whole_ref /home/shuaiw/borg/paper/run2/SRR23446540_sugarcane/SRR23446540_sugarcane.hifiasm.p_ctg.rename.fa \
                --read_type hifi \
                --min_len 1000 \
                --max_NM 30000000 \
                --min_cov 1 \
                --min_frac 0.4 \
                --min_score 30 \
                --min_sites 30 \
                --mge_file /home/shuaiw/borg/paper/run2/SRR23446540_sugarcane/all_mge.tsv \
                --threads 64" \
                --job-name=SRR23446540_sugarcane_test
